//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoDef.proto
namespace ProtoDef
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Sql_Result_Login")]
  public partial class Sql_Result_Login : global::ProtoBuf.IExtensible
  {
    public Sql_Result_Login() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _createtime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private long _logintime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"logintime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long logintime
    {
      get { return _logintime; }
      set { _logintime = value; }
    }
    private ulong _phone;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private long _email;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long email
    {
      get { return _email; }
      set { _email = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Log_SYUC_Login")]
  public partial class Log_SYUC_Login : global::ProtoBuf.IExtensible
  {
    public Log_SYUC_Login() {}
    
    private string _file_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"file_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string file_name
    {
      get { return _file_name; }
      set { _file_name = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _log;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string log
    {
      get { return _log; }
      set { _log = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sqlresult_usercenterserver_uid")]
  public partial class sqlresult_usercenterserver_uid : global::ProtoBuf.IExtensible
  {
    public sqlresult_usercenterserver_uid() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sqlresult_usercenterserver_count")]
  public partial class sqlresult_usercenterserver_count : global::ProtoBuf.IExtensible
  {
    public sqlresult_usercenterserver_count() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sqlresult_usercenterserver_uid_session")]
  public partial class sqlresult_usercenterserver_uid_session : global::ProtoBuf.IExtensible
  {
    public sqlresult_usercenterserver_uid_session() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _session;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sqlresult_usercenterserver_b")]
  public partial class sqlresult_usercenterserver_b : global::ProtoBuf.IExtensible
  {
    public sqlresult_usercenterserver_b() {}
    
    private bool _b;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool b
    {
      get { return _b; }
      set { _b = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Web_SYUC_Test")]
  public partial class Web_SYUC_Test : global::ProtoBuf.IExtensible
  {
    public Web_SYUC_Test() {}
    
    private string _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"webresult_usercenterserver_login")]
  public partial class webresult_usercenterserver_login : global::ProtoBuf.IExtensible
  {
    public webresult_usercenterserver_login() {}
    
    private E_SYUC_RET_CODE _ret_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public E_SYUC_RET_CODE ret_code
    {
      get { return _ret_code; }
      set { _ret_code = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _session;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"E_SYUC_RET_CODE")]
    public enum E_SYUC_RET_CODE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RC_OK", Value=0)]
      RC_OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RC_YES", Value=1)]
      RC_YES = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RC_NO", Value=2)]
      RC_NO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RC_FAILURE", Value=-1)]
      RC_FAILURE = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RC_PARAMETER_ERROR", Value=-2)]
      RC_PARAMETER_ERROR = -2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"E_MSG_TYPE")]
    public enum E_MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_C2S_Ask_Login", Value=1)]
      Msg_C2S_Ask_Login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_S2C_Ret_Login", Value=2)]
      Msg_S2C_Ret_Login = 2
    }
  
}